add my works
LiteLDev/Registry pull request #11
Opened 2023-03-08 18:45 UTC by lgc2333

2023-03-08 23:21 UTC, Futrime commented
Failed to build, please check again.

2023-03-08 23:25 UTC, WangYneos commented
建议不要提交已停更/放弃维护的插件

2023-03-08 23:27 UTC, Futrime commented
author field should only contains [a-zA-Z0-9-]+, you are recommended to use your github username.

2023-03-09 07:50 UTC, lgc2333 commented
okay

2023-03-09 22:41 UTC, Futrime requested changes

2023-03-09 22:41 UTC, Futrime commented on teeth/formapiex.json
> +      "module",
This is a plugin rather than a module. Module is restricted to ll modules.

2023-03-09 22:41 UTC, Futrime commented on teeth/navigationapi.json
> +    "tags": ["module", "llse", "navigate", "navigation", "api", "navigationapi"]
Not a module

2023-03-10 08:20 UTC, Futrime approved these changes

2023-03-10 08:22 UTC, merged